# (C) Serge Victor 2020-2024, GPLv3 License
# 
# recently build version of documents is available on permanent storage disk mounted on /LDP

kind: pipeline
type: docker
name: 🗃 LDP Builder

workspace:
  path: /builder/src
   
steps:
- name: Martin's builder
  image: tldp/builder:latest
  commands:
  - ldptool --dump-cfg
  - mkdir -p /builder/LDP/BUILD
  - mkdir -p /builder/LDP/MAIN
  - ldptool --loglevel info --builddir /builder/LDP/BUILD --configfile .github/builder-pr.ldptool.cfg --pubdir /builder/LDP/MAIN --list
  - ldptool --loglevel info --builddir /builder/LDP/BUILD --configfile .github/builder-pr.ldptool.cfg --pubdir /builder/LDP/MAIN --publish
