---
# (C) Dr Serge Victor 2020-2025, GPLv3 License
# (C) The Linux Documentation Project 2020-2025, GPLv3 License
# 
# recently build version of documents is available on permanent storage disk mounted on /LDP
#
# this file is protected, DO NOT TAMPER without permission from LDP authorised maintainers!
# contact us or create an issue before thinking about any changes.

steps:
#####

# PUBLIC ACCESS VIA PULL REQUESTS

- name: 🗃 Martin's builder - Pull Request only (partial build)
  image: tldp/builder:latest
  directory: /builder
  when:
    - event: pull_request
      branch: master
  commands:
  - mkdir -p /builder/BUILD
  - mkdir -p /builder/PUBDIR
  - whoami
  - pwd
  - ldptool --dump-cfg
  - rsync -av /LDP-ro/en /builder/BUILD
  - ldptool --loglevel info --builddir /builder/BUILD --configfile $GITDIR/.github/builder.ldptool.cfg --pubdir /builder/PUBDIR --list
  - ionice -c 3 chrt --idle 0 ldptool --loglevel info --builddir /builder/BUILD --configfile $GITDIR/.github/builder.ldptool.cfg --pubdir /builder/PUBDIR --publish

- name: ⇡⇡ Upload artifacts to our S3
  image: tldp/woodpecker-rclone
  when:
    - event: pull_request
      branch: master
  settings:
    rclone_config: 
      from_secret: RCLONE_RW
    subcommand: sync
    commandline: /builder/PUBDIR/ LDP:ldp-pr/${CI_BUILD_NUMBER}

# ADMINS ONLY ACCESS

- name: 🗃 Martin's builder - all revieved commits (full build)
  image: tldp/builder:latest
  directory: /builder
  environment:
    GITDIR: /woodpecker/src/github.com/ser/LDP
  volumes:
    - /LDP:/LDP
  when:
    - event: [ push, pull_request_closed, cron, manual ]
  commands:
  - mkdir -p /builder/BUILD
  - mkdir -p /builder/PUBDIR
  - whoami
  - pwd
  - ldptool --dump-cfg
  - ldptool --loglevel info --builddir /builder/BUILD --configfile $GITDIR/.github/builder.ldptool.cfg --pubdir /builder/PUBDIR --list
  - ionice -c 3 chrt --idle 0 ldptool --loglevel info --builddir /builder/BUILD --configfile $GITDIR/.github/builder.ldptool.cfg --pubdir /builder/PUBDIR --publish
  - rsync -av --delete-after /builder/PUBDIR/ /LDP/en
  - cd $GITDIR
  - git rev-parse HEAD > /LDP/last-commit-id.txt
  - date > /LDP/build-date.txt

#- name: ⇡⇡ Upload full build to our S3
#  image: tldp/woodpecker-rclone
#  volumes:
#    - /LDP:/LDP
#  when:
#    - event: [ push, pull_request_closed, cron, manual ]
#  settings:
#    rclone_config: 
#      from_secret: RCLONE_RW
#    subcommand: sync
#    commandline: /LDP/ LDP:ldp

# the happy end.
