---
# (C) Serge Victor 2020-2024, GPLv3 License
# 
# recently build version of documents is available on permanent storage disk mounted on /LDP
#
# this file is protected, DO NOT TAMPER without permission from LDP authorised maintainers!
# contact us or create an issue before thinking about any changes.

#kind: pipeline
#type: docker
#name: 🗃 LDP Builder

#workspace:
#  path: /builder/src
   
steps:
- name: 🗃 Martin's builder - Pull Request only (partial build)
  image: tldp/builder:latest
  volumes:
    - /LDP:/LDP
  when:
    - event: pull_request
      branch: master
  commands:
  - pwd
  - ldptool --dump-cfg
  - rm -rf /LDP/PR
  - mkdir -p /LDP/PR/BUILD
  - rsync -av /LDP/en /LDP/PR
  - ldptool --loglevel info --builddir /LDP/PR/BUILD --configfile .github/builder.ldptool.cfg --pubdir /LDP/PR/en --list
  - ionice -c 3 chrt --idle 0 ldptool --loglevel info --builddir /LDP/PR/BUILD --configfile .github/builder.ldptool.cfg --pubdir /LDP/PR/en --publish
  - git rev-parse HEAD > /LDP/PR/last-commit-id.txt
  - date > /LDP/PR/build-date.txt

- name: 🗃 Martin's builder - all revieved commits (full build)
  image: tldp/builder:latest
  directory: /builder
  volumes:
    - /LDP:/LDP
  when:
    - event: [ push, pull_request_closed, cron, manual ]
  commands:
  - mkdir -p /builder/src/BUILD
  - mkdir -p /builder/src/PUBDIR
  - whoami
  - pwd
  - ldptool --dump-cfg
  - ldptool --loglevel info --builddir /builder/src/BUILD --configfile /woodpecker/src/github.com/ser/LDP/.github/builder.ldptool.cfg --pubdir /builder/src/PUBDIR --list
  - ionice -c 3 chrt --idle 0 ldptool --loglevel info --builddir /builder/src/BUILD --configfile .github/builder.ldptool.cfg --pubdir /builder/src/PUBDIR --publish
  - rsync -av --delete-after /builder/src/PUBDIR/ /LDP/en
  - git rev-parse HEAD > /LDP/last-commit-id.txt
  - date > /LDP/build-date.txt

# the happy end.
#---
#kind: signature
#hmac: fd968948e59d4b913d5de111f9d1af439186143a68e3ee7558e61287b804b974
#
#...
