---
# (C) Dr Serge Victor 2020-2025, GPLv3 License
# (C) The Linux Documentation Project 2020-2025, GPLv3 License
# 
# recently build version of documents is available on permanent storage disk mounted on /LDP
#
# this file is protected, DO NOT TAMPER without permission from LDP authorised maintainers!
# contact us or create an issue before thinking about any changes.

steps:
#####

# PUBLIC ACCESS VIA PULL REQUESTS

- name: 🗃 Martin's builder - Pull Request only (partial build)
  image: tldp/builder:latest
  environment:
    GITDIR: /woodpecker/src/github.com/ser/LDP
  when:
    - event: pull_request
      branch: master
  commands:
  - mkdir -p /woodpecker/BUILD
  - mkdir -p /woodpecker/PUBDIR
  - whoami
  - pwd
  - ldptool --dump-cfg
  - rsync -av /LDP-ro/en/ /woodpecker/PUBDIR
  - ldptool --loglevel info --builddir /woodpecker/BUILD --configfile $GITDIR/.github/builder.ldptool.cfg --pubdir /woodpecker/PUBDIR --list
  - ionice -c 3 chrt --idle 0 ldptool --loglevel info --builddir /woodpecker/BUILD --configfile $GITDIR/.github/builder.ldptool.cfg --pubdir /woodpecker/PUBDIR --publish

- name: ⇡⇡ Upload artifacts to our S3
  image: tldp/woodpecker-rclone
  when:
    - event: pull_request
      branch: master
  settings:
    rclone_config: 
      from_secret: RCLONE_RW
    subcommand: --copy-links sync 
    commandline: /woodpecker/PUBDIR/ LDP:ldp-pr/${CI_PIPELINE_NUMBER}

- name: ☭ Comment the PR with links to S3
  image: quay.io/thegeeklab/wp-github-comment
  settings:
    api_key:
      from_secret: GITHUB_PR
    message: "CI run completed successfully: {CI_PIPELINE_URL}"
    update: true

# ADMINS ONLY ACCESS

- name: 🗃 Martin's builder - all revieved commits (full build)
  image: tldp/builder:latest
  environment:
    GITDIR: /woodpecker/src/github.com/ser/LDP
  volumes:
    - /LDP:/LDP
  when:
    - event: [ push, pull_request_closed, cron, manual ]
  commands:
  - mkdir -p /woodpecker/BUILD
  - mkdir -p /woodpecker/PUBDIR
  - whoami
  - pwd
  - ldptool --dump-cfg
  - ldptool --loglevel info --builddir /woodpecker/BUILD --configfile $GITDIR/.github/builder.ldptool.cfg --pubdir /woodpecker/PUBDIR --list
  - ionice -c 3 chrt --idle 0 ldptool --loglevel info --builddir /woodpecker/BUILD --configfile $GITDIR/.github/builder.ldptool.cfg --pubdir /woodpecker/PUBDIR --publish
  - rsync -av --delete-after /woodpecker/PUBDIR/ /LDP/en
  - cd $GITDIR
  - git rev-parse HEAD > /LDP/last-commit-id.txt
  - date > /LDP/build-date.txt

#- name: ⇡⇡ Upload full build to our S3
#  image: tldp/woodpecker-rclone
#  volumes:
#    - /LDP:/LDP
#  when:
#    - event: [ push, pull_request_closed, cron, manual ]
#  settings:
#    rclone_config: 
#      from_secret: RCLONE_RW
#    subcommand: sync
#    commandline: /LDP/ LDP:ldp

# the happy end.
