# (C) Serge Victor 2020, GPLv3 License
# 
# recently build version of documents is available on permanent storage disk mounted on /LDP

kind: pipeline
type: docker
name: 🗃 LDP Builder
   
steps:
- name: Martin's builder
  image: tldp/builder:latest
  commands:
  - ldptool --dump-cfg
  - rm -rf /LDP/BUILD
  - rm -rf /LDP/MAIN
  - mkdir -p /LDP/BUILD
  - mkdir -p /LDP/MAIN
  - rsync -av /LDP/WWW/en/ /LDP/MAIN
  - ldptool --loglevel info --builddir /LDP/BUILD --configfile .github/builder-pr.ldptool.cfg --pubdir /LDP/MAIN --list
  - ldptool --loglevel info --builddir /LDP/BUILD --configfile .github/builder-pr.ldptool.cfg --pubdir /LDP/MAIN --publish
  - rsync -av --delete-after /LDP/MAIN/ /LDP/WWW/en
